### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by InvisibleSpiders** [GroupeZ-dev/Plugins-Report#1]
### Terms

- [X] I'm using the very latest version of the plugin.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/GroupeZ-dev/Plugins-Report/issues) and haven't found any.
- [X] I already searched on the plugin wiki to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

InvisibleSpiders

### Plugin

zEssentials

### Server Version

1.21.3

### Server Software

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-80-c2294d7 (MC: 1.21.3)

### Plugin Version

zEssentials 1.0.1.5
zMenu 1.0.3.6

### What happened?

Error occurs with newest version:

The error below occurs after updating to the most recent version. 

### Steps to reproduce the issue

Plugin worked fine before update. 
With MySQL set up and functioning on prior version, update to recent version, then restart server and observe console.

### Full Server Log

https://mclo.gs/dTxMeKF

### Error (optional)

```shell
[18:20:33 INFO]: [com.zaxxer.hikari.HikariDataSource] sarah-0 - Starting...
[18:20:34 INFO]: [com.zaxxer.hikari.HikariDataSource] sarah-0 - Start completed.
[18:20:34 INFO]: [zEssentials] The database connection is valid ! (us-mysql-01.rawpower.network)
[18:20:34 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'No reason' in 'DEFAULT'
[18:20:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
[18:20:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
[18:20:34 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:612)
[18:20:34 WARN]:        at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:320)
[18:20:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:382)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.requests.AlterRequest.execute(AlterRequest.java:51)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.SchemaBuilder.execute(SchemaBuilder.java:648)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.MigrationManager.lambda$execute$2(MigrationManager.java:58)
[18:20:34 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.libs.sarah.MigrationManager.execute(MigrationManager.java:54)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.storage.storages.SqlStorage.<init>(SqlStorage.java:173)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.storage.ZStorageManager.<init>(ZStorageManager.java:34)
[18:20:34 WARN]:        at zEssentials-1.0.1.5.jar//fr.maxlego08.essentials.ZEssentialsPlugin.onEnable(ZEssentialsPlugin.java:204)
[18:20:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:20:34 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:20:34 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:20:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:20:34 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[18:20:34 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[18:20:34 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768)
[18:20:34 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530)
[18:20:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326)
[18:20:34 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235)
[18:20:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340)
[18:20:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Maxlego08** [comment]
You can show me the contents of the migration table and the contents of the transactions economy table

**Comment by InvisibleSpiders** [comment]
How do I do that? 

I don't use the economy module

**Comment by Maxlego08** [comment]
Give me your database.db file, you can send me that on discord

**Comment by InvisibleSpiders** [comment]
Where would I find that?
I checked all the zEssentials files and there is no database.db file.
I have mine set to use MySQL.

**Comment by InvisibleSpiders** [comment]
I'll send the info, but I still don't know where to get the file you're requesting

**Comment by Maxlego08** [comment]
Duplicate and already fixed: https://github.com/Maxlego08/zEssentials/issues/145
