### ISSUE TITLE
Superior SkyBlock -Zmenu Island Storage Opens incorrect players storage (opens last not own )

### ISSUE THREAD

**Issue by RustyDagger** [GroupeZ-dev/Plugins-Report#2]
### Terms

- [X] I'm using the very latest version of the plugin.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/GroupeZ-dev/Plugins-Report/issues) and haven't found any.
- [X] I already searched on the plugin wiki to know if a solution is already known.
- [X] I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this.
- [X] I enabled the debug mode in config.yml and sql debug

### Discord Username (optional)

RustyDagger

### Plugin

SuperiorSkyBlock-zMenu

### Server Version

1.21.4

### Server Software

[09:28:46]: Checking version, please wait...
[09:28:47]: This server is running Paper version 1.21.3-76-master@27e4ddc (2024-11-30T10:07:53Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-39-fdef6d3 (MC: 1.21.3)

### Plugin Version

[09:30:05]: SuperiorSkyblock2 version 2024.3-zMenu
16/12/2024 [09:30:05]: Feature packed Skyblock core.
16/12/2024 [09:30:05]: Website: https://bg-software.com/
16/12/2024 [09:30:05]: Author: Ome_R

### What happened?

Opens the chest menu too the last one viewed instead of the correct chests for the player clicking it.
Mostly Noticeable when using admin command to view other islands chests then clicking the zmenu button to open this menu.

I suspect this menu could benefit from having an argument added called "player"  so the menu could be opened defaulty to the player clicking it but also for someone else ( like the admin command allows ) 

### Steps to reproduce the issue

1. Two players yourself and another.
2. Have player 2 place something in their storage chest
3. check your own storage chest. make sure its different.
4. use /is admin chest <nameofplayer2Island>
5. observe their island chest contents.
6. Open any menu and click a button containing this.

```
  island_vault:
    type: INVENTORY
    inventory: island-chests
    plugin: SuperiorSkyblock2
    slot: 12
    item:
      material: ENDER_CHEST
      amount: 1
      name: "&aɪѕʟᴀɴᴅ ᴠᴀᴜʟᴛѕ"
```

7. when clicked you should be shown the menu to select a storage to open. This is where its broken it will show Player 2's items again. ( it should show your own ) 
8. if you type /is chest. close the menu then click the same button from step 6 you will be shown your own items again.

### Full Server Log

Not relavant / nothing to see.

**Comment by RustyDagger** [comment]
I think this is kind of related when a player logs in, the plugin sometimes will not open a menu until after a default skyblock command has been "used" i think using the command loads in the island instance that will then be used for any menu thats then opend with the "inventory button code from above"

```
22/12/2024 [22:57:29 ERROR]: Could not pass event InventoryClickEvent to zMenu v1.0.3.6
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.island.Island.getUpgradeLevel(com.bgsoftware.superiorskyblock.api.upgrades.Up
grade)" because "island" is null
    at SuperiorSkyblock2-2024.3-zMenu.jar/com.bgsoftware.superiorskyblock.core.zmenu.buttons.UpgradeButton.checkPermission(UpgradeButton.java:35) ~[SuperiorSkyb
lock2-2024.3-zMenu.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.inventories.InventoryDefault.buildButton(InventoryDefault.java:144) ~[zmenu-1.0.3.6.jar:?]
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.inventories.InventoryDefault.lambda$openInventory$4(InventoryDefault.java:85) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.inventories.InventoryDefault.openInventory(InventoryDefault.java:100) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.VInventory.preOpenInventory(VInventory.java:160) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.VInventoryManager.createInventory(VInventoryManager.java:100) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.VInventoryManager.createInventory(VInventoryManager.java:66) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.zcore.utils.ZUtils.createInventory(ZUtils.java:484) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.ZInventoryManager.openInventory(ZInventoryManager.java:276) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.button.buttons.ZInventoryButton.onClick(ZInventoryButton.java:69) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.inventories.InventoryDefault.lambda$displayFinalButton$10(InventoryDefault.java:210) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.zcore.utils.inventory.ItemButton.onClick(ItemButton.java:66) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.inventory.VInventoryManager.onInventoryClick(VInventoryManager.java:154) ~[zmenu-1.0.3.6.jar:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.listener.AdapterListener.lambda$onInventoryClick$2(AdapterListener.java:59) ~[zmenu-1.0.3.6.jar:?]
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
    at zmenu-1.0.3.6.jar/fr.maxlego08.menu.listener.AdapterListener.onInventoryClick(AdapterListener.java:59) ~[zmenu-1.0.3.6.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor930.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-76-27e4ddc]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-76-27e4ddc]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3250) ~[paper-1.21.3.jar:1.21.3-76-27e4d
dc]

```


Im pretty sure the inventory button code is not allocating the player/players island correctly when its used it needs to take the player as an argument when its opened.

this login bug can be demonstrated by:
1. login to the server
2. open another players /is admin chest <someotherplayersisland>
3. open a button with the code from the above error. to say the upgrades menu
4. observe that the upgrades menu you see is not the upgrades menu for your own island but it is the upgrade menu for the player from step 2.

again this is because its just opening the menu from the last island it had from the plugin and when you fresh join theres no last viewed island so its null and causes the error above. its not fetching the island when a menu is opened.
